# Generated by Django 4.2.29 on 2026-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_farm_location_userprofile_farm_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('agronomist', 'Agronomist')], default='farmer', max_length=20),
        ),
    ]
