# Generated by Django 4.2.29 on 2026-03-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_consultation_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('HELD_IN_ESCROW', 'Held in Escrow')], default='PENDING', max_length=20),
        ),
    ]
