# Generated by Django 4.2.29 on 2026-03-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_consultant_user_userprofile_documents_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='expertise_category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='consultant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultant',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expertise_category',
            field=models.CharField(choices=[('Agronomy', 'Agronomy'), ('Livestock', 'Livestock'), ('Soil Health', 'Soil Health'), ('Pest Control', 'Pest Control'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
