# Generated by Django 4.2.29 on 2026-03-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='expertise_category',
            field=models.CharField(blank=True, default='General', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
